### ISSUE TITLE
Problem connecting to port 56709

### ISSUE THREAD

**Issue by egll-tech** [NicholeMattera/OJDS-NX#6]
Is there any way to enable/disable the server or to indicate which port to use? For some reason when I wake up my switch it doesn't allow me to connect again

**Comment by KernelZechs** [comment]
@egll-tech it's uPNP port for OJD, likely you have uPNP blocked on your machine or router. I would check your router settings for this first and then look at your PCs firewall. For some low-end/gaming routers this may be under the name of 'game routing' or 'xbox routing' or something similar, check your routers manual. Otherwise there should be a setting for uPNP.

**Comment by egll-tech** [comment]
@KernelZechs it works, but only when I restart the switch into Atmosphere. If I leave it in the dock for a while and then come back later (wake up the switch) it stops working. Any idea how to avoid this?
